# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Node.js package to portfolio website

on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.6
      - run: npm ci
      - run: npm test


  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    defaults:
      run:
        working-directory: ./development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 18.6
          npm-version: 9.7.1

      - name: Install and Build
        run: |
          node -v
          npm -v
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: development/build
          token: ${{ secrets.PORTFOLIO_DEPLOY }}
